name: Deploy Lambda Function

on:
  push:
    branches:
      - main
    paths:
      - "lambda_function.py"
      - ".github/workflows/deploy-lambda.yml"

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show GitHub OIDC claims
        shell: bash
        run: |
          TOKEN=$(curl -sLS \
            -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
            "${ACTIONS_ID_TOKEN_REQUEST_URL}&audience=sts.amazonaws.com" | jq -r '.value')

          PAYLOAD=$(echo "$TOKEN" | cut -d '.' -f2)
          PAYLOAD="${PAYLOAD//-/+}"
          PAYLOAD="${PAYLOAD//_/\/}"

          case $((${#PAYLOAD} % 4)) in
            2) PAYLOAD="${PAYLOAD}==" ;;
            3) PAYLOAD="${PAYLOAD}=" ;;
          esac

          echo "$PAYLOAD" | base64 -d 2>/dev/null | jq '{sub, aud, repository, ref}'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ap-south-1

      - name: Create deployment package
        run: |
          zip function.zip lambda_function.py

      - name: Update Lambda function
        run: |
          aws lambda update-function-code \
            --function-name shruti--12 \
            --zip-file fileb://function.zip
