name: Deploy Lambda Function

on:
  push:
    branches:
      - main
    paths:
      - "lambda_function.py"
      - ".github/workflows/deploy-lambda.yml"

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ap-south-1

      - name: Create deployment package
        run: |
          zip function.zip lambda_function.py

      - name: Update Lambda function
        run: |
          aws lambda update-function-code \
            --function-name shruti--12 \
            --zip-file fileb://function.zip
